export { default as HomePage } from "./HomePage";
export { default as Landing } from "./Landing";
export { default as JoinCommunity } from "./JoinCommunity";
export { default as PopularServices } from "./PopularServices";
export { default as PopularCategories } from "./PopularCategories";
export { default as PeopleSection } from "./PeopleSection";
export { default as HowWorksSection } from "./HowWorksSection";
export { default as RandomServices } from "./RandomServices";
export { default as UnderConstruction } from "./UnderConstruction";
